{% set data = load_setup_py_data() %}

package:
    name    : typhos
    version : {{ data.get('version') }}

source:
    path: ..

requirements:
    build:
      - python
      - setuptools


    run:
      - python
      - coloredlogs
      - happi
      - numpy
      - ophyd >=1.2.0
      - pyqtgraph
      - pydm >=1.6.0
      - qdarkstyle
      - qtawesome
      - qtconsole
      - qtpy
      - timechart
      - numpydoc

about:
  home: https://github.com/pcdshub/typhos
  license: SLAC Open License
  summary: Automatic User Interface Creation from Ophyd Devices
